### ISSUE TITLE
Middleware does not get applied in private routes

### ISSUE THREAD

**Issue by Qodestackr** [Abdullah-dev0/Authjs-starter-pack#1]
Hello, I picked this template to build a project on it but can notice that session is not applied in private routes when i build in vercel..

**Comment by Qodestackr** [comment]
@Abdullah-dev0

**Comment by Qodestackr** [comment]
Fix: Deleted the Middleare and used Page Level Session checks and works flawlessly.

**Comment by Abdullah-dev0** [comment]
> Fix: Deleted the Middleare and used Page Level Session checks and works flawlessly.

make a pull request let me see also !
